### ISSUE TITLE
Template for BioCypher gives error

### ISSUE THREAD

**Issue by Valentijn000** [biocypher/biocypher#159]
Dear friends, 

Today, I cloned the BioCypher project template, according to the instructions given. I am a bit of of a novice, but once I figured out I had to install the poetry package, and adjust the $PATH variable, everything seemed to work. The last command however (python create_knowledge_graph.py)  produced a list of errors. I am not sure whether this is due to some of my settings not being correct, or whether there is an actual error in the script. I include a screenshot of the git bash shell.  Hope you are able to tell what went wrong. 

All in all, I am really motivated after reading your paper on BioCypher to get this up and running. It seems just what I need to create the complex FAIR data objects supporting the research project I am in the process of initiating.

Thank you!

Valentijn  

<img width="943" alt="Screenshot 2023-03-16 175156" src="https://user-images.githubusercontent.com/128058995/225698673-120c4604-fec7-4d43-b618-9f10e1702159.png">

**Comment by slobentanzer** [comment]
Hi Valentijn,
great that you like BioCypher, and thanks for the report.

This is an issue with your system encoding; you need to use UTF-8 instead of the Windows-1252 (cp1252) encoding you are using in your environment. There are multiple ways of doing that, you can see which one is the right for you. There are many tutorials, such as this: https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

Give it a shot and let me know if you still have problems.

**Comment by Valentijn000** [comment]
Hi Sebastian, 

Thanks for your quick reply: that solved the problem. I will follow your advice and join the chat. It'll be very helpful to me to discuss my project with others!

Enjoy your day. 

Valentijn

**Comment by slobentanzer** [comment]
Hi @Valentijn000,
it is good practice to close an issue once it is solved (from the opener's side).

Kind regards
Sebastian

**Comment by Valentijn000** [comment]
Hi Sebastian, 

Thanks for pointing this out, I didn't know. Will do. 

Best,

Valentijn
