### ISSUE TITLE
Lorem ipsum instead of random letters in data generator

### ISSUE THREAD

**Issue by slobentanzer** [biocypher/biocypher#253]
review comment: We feel that it would improve the examples, if the data generator created
description fields with actual text (like lorem ipsum), rather than just
random letters.

**Comment by slobentanzer** [comment]
@nilskre maybe look at this dataset: https://ogb.stanford.edu/docs/linkprop/#ogbl-biokg

**Comment by nilskre** [comment]
After looking into this in detail, some thoughts came up.

Specific comments for the dataset:
- The dataset does not contain node features. So there only exists the id of the Protein and a mapping table to map the ids to the underlying Protein ID within a Protein database. Thus, the dataset does not contain the data we need to build up the tutorial (in the tutorial the Protein sequence is used).

General thoughts:
- For new users the tutorial is one of the first touchpoints with BioCypher. 
- On the one hand the usage of a real dataset in the tutorial makes this introduction more realistic.
- On the other hand the increased technical complexity could lead to new unknown errors when running the tutorial (e.g. the download of the dataset already took 5 mins). In the worst case, this could scare off potential new users.

Suggestion:
=> Leave the tutorial as it is, because the core concepts can be easily explained in this toy example scenario.
To improve the readability two suggestions:
- Decrease the randomly generated sequence length to improve readability.
- some real text as description field (to impede the confusion with the Portein sequence).

**Comment by slobentanzer** [comment]
I agree; the tutorial should remain very simple and fast.

The dataset could be a nice foundation for building a more realistic advanced demo (like pole but biomed-related), but that shouldn't be the focus of the basic tutorial.
