### ISSUE TITLE
How to add new database like i want to add "Human Phenotype Ontology" using open-target.

### ISSUE THREAD

**Issue by shaileshchaudhary11** [biocypher/biocypher#362]
I want to add complete database from link "https://platform.opentargets.org/downloads" what are the file should i changed to achive this thing. I am using "https://github.com/biocypher/project-template" and "https://github.com/biocypher/open-targets" using this i able to see 6 databases in neo4j. I need to import complete database.

**Comment by slobentanzer** [comment]
Hi @shaileshchaudhary11,
I am afraid I need more details to answer your question. Basically (as the docs and readme state), our open-targets pipeline is a prototype with a limited subset of open targets data. You should not need the template as well, because open-targets already is a pipeline. I am not sure how you use them together.

If you want to add more data types, you need to add them to the open-targets adapter (ETL-style), and then you would ideally open a PR once you have added a data type, so that other users also have access.

**Comment by shaileshchaudhary11** [comment]
Thankyou for your response @slobentanzer  i am now able to generate nodes for Human Phenotype Ontology dataset by modifying  open-target (target_disease_evidence_adapter.py, target_disease_script.py and schema_config.yaml) files.
