### ISSUE TITLE
Duplicate removal in Open-Targets Data.

### ISSUE THREAD

**Issue by rahulmaurya1507** [biocypher/biocypher#367]
I was going to through the adapter file for open-targets dataset in which I found that the `MouseTargetNodeField` has de-duplication (dropDuplicates()) on rows. On deeper investigation, I found that the `biocypher` is not generating nodes for repeated primary ids. Dropping duplicates if the whole row is same is fine. But, many of the rows whose primary id's are same but the other fields are different. 
Isn't doing deduplication on primary id's is making us loose a lot of data ndoes? I humbly request you to go through my issue and help me understand it.

I am attaching some code snippets for the reference:

```python
import pandas as pd


df = pd.read_parquet('data/ot_files/mousePhenotypes/part-00000-48207836-4496-49fb-93e0-08dfd41e5c98-c000.snappy.parquet')

mouse_target = df[['targetInModelEnsemblId', 'targetInModel', 'targetInModelMgiId', 'targetFromSourceId']]
print(mouse_target.shape) #-> (206307, 4)
dedup_mt = mouse_target.drop_duplicates()
print(dedup_mt.shape) #->(12907, 4)
col_dup_mt = mouse_target.drop_duplicates(subset='targetInModelEnsemblId')
print(col_dup_mt.shape) #-> (12021, 8)

The above script gives the idea about the original data, row deduplicator and deduplication on the primary id.

```markdown
1. Many primary ids are same but the data is different.
8[{'allelicComposition': 'AU040320<em1(IMPC)J> hom late', 'geneticBackground': 'C57BL/6NJ', 'id': 'MGI:5803696', 'literature': None}]                                                                    [{'id': 'MP:0005375', 'label': 'adipose tissue phenotype'}]       MP:0010024                     increased total body fat amount    ENSG00000142687       AU040320     ENSMUSG00000028830        MGI:2140475
9[{'allelicComposition': 'AU040320<em1Janc>/AU040320<em2Janc>', 'geneticBackground': 'FVB/N-AU040320<em1Janc> AU040320<em2Janc>', 'id': 'MGI:5911090', 'literature': ['26814968']}]                                                                     [{'id': 'MP:0005387', 'label': 'immune system phenotype'}]       MP:0020923  decreased susceptibility to Parvoviridae infection    ENSG00000142687       AU040320     ENSMUSG00000028830        MGI:2140475
```
the above example is from MousePhenotypes data where the  multiple rows have same primary id but the other details are different. I believe there should be two nodes from them by using some logic.

```python
# Mouse Targets
        mouse_target_df = self.mp_df.select(
            [field.value for field in MouseTargetNodeField]
        ).dropDuplicates()
        yield from self._yield_node_type(
            mouse_target_df, MouseTargetNodeField, "ensembl"
        )
```

This is the part which contains the deduplocation on rows in `otar_biocypher/target_disease_evidence_adapter.py` file.

**Comment by slobentanzer** [comment]
Hi @rahulmaurya1507 ,
thanks for sticking with the issue! I now see what's going on. The choice of how to create a node's primary ID is subtle; for this reason we don't make prescriptions. In many database systems, you cannot have nodes with the same primary ID, which is why we deduplicate. We also log the deduplication to be transparent about which data is discarded, you can find it in the log.

When I have an issue like the one you are describing, I try to either 1) use the database schema to circumvent the problem, or to 2) generate new unique identifiers using more information from each row. I'll describe below:

1. If the entity the primary identifier refers to is indeed a unique entity, then the columns that are removed upon deduplication should probably be separate entities. In the case of the mice: if the unique ID of the mouse is the species, but it has different genetic backgrounds, you could create a separate node for the GeneticBackground, and introduce an edge from each primary ID case to the genetic background in each row, adding other entities and relationships as needed. This will change the schema of your KG, which you need to account for in the configuration as well.

2. If you want to (and can) change your primary identifier system, you can also use the additional information in each row to do that. I usually use md5 hashes: collect all parts of the row that you want to be included in the uniqueness of the ID of the row, and then use hashlib or some other way of encoding this collected information into an md5 hash. In the case above, you could use the columns you want to encode, such as `allelicComposition`, `geneticBackground`, etc., to generate your unique identifiers and then pass those to BioCypher to create the nodes (as the first element of the tuple). In this case, you need to account for the new identifiers in all other contexts of the graph, i.e., if you want to create edges to or from these nodes.

Does this make sense? Let me know if this solves your problem or whether you need more specific input on one of the cases.

**Comment by rahulmaurya1507** [comment]
This is a wonderful explanation which answers all my questions for now. I'm still trying to understand the edges generation part. I did foresee that if I make alternative primary Id, I would need to account for changes in edges generation. I am trying to create a sample custom edge for my understanding. Once I'm able to do it, I might ask some new question.

Thank you again,
Regards
